// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://denixywtzwkwndqeoeeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbml4eXd0endrd25kcWVvZWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzcwOTIsImV4cCI6MjA3MjY1MzA5Mn0.gNSWMSetDGOLK0o_W-Inx6-wnqqk7AEhdUfHx1ebE8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});